[package]
name = "lagon-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
lagon-runtime = { path = "../runtime" }
clap = { version = "4.0.7", features = ["derive"] }
dialoguer = "0.10.2"
indicatif = "0.17.1"
colored = "2.0.0"
dirs = "4.0.0"
webbrowser = "0.8.0"
tokio = { version = "1", features = ["full"] }
hyper = { version = "0.14", features = ["client", "server", "http1", "http2", "runtime"] }
mime = "0.3.16"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
walkdir = "2.3.2"
pathdiff = "0.2.1"
hyper-tls = { version = "0.5.0", features = ["vendored"] }
flume = "0.10.14"
chrono = "0.4.22"
notify = "5.0.0"
